# Generated by Django 3.0.7 on 2021-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 날짜입니다.', verbose_name='수정 일시')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='활성화할지 여부를 결정합니다.', verbose_name='활성화 여부')),
                ('shop', models.CharField(help_text='의류 판매업체 상호 명을 나타냅니다.', max_length=50, verbose_name='의류 판매업체')),
                ('box_size', models.CharField(blank=True, default='50', help_text='추천목록 상자의 크기(%)를 나타냅니다.', max_length=20, verbose_name='추천목록 상자 크기')),
                ('num_of_item', models.IntegerField(blank=True, default=5, help_text='추천목록의 아이템 개수를 나타냅니다.', verbose_name='추천 아이템 개수')),
                ('item_size', models.CharField(blank=True, default='20', help_text='박스내 추천 아이템들의 크기(%)를 나타냅니다.', max_length=20, verbose_name='이름')),
                ('custom_item_src', models.CharField(blank=True, help_text='사용자 설정 아이템 주소를 나타냅니다.', max_length=200, null=True, verbose_name='사용자 설정 아이템 주소')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
